services:
  app:
    container_name: doc2loc
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/doc2loc?authSource=admin
      - NODE_ENV=production
    working_dir: /opt/doc2loc
    volumes:
      - ./uploads:/opt/doc2loc/uploads
      - node_modules:/opt/doc2loc/node_modules
    networks:
      - doc2loc-net
    restart: unless-stopped

networks:
  doc2loc-net:
    external: true

volumes:
  node_modules:
