services:
  app:
    container_name: doc2loc
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=production
    working_dir: /opt/doc2loc
    volumes:
      - ./uploads:/opt/doc2loc/uploads
    networks:
      - doc2loc-net
    restart: unless-stopped

networks:
  doc2loc-net:
    external: true
