const DEVICES = {
  mobile320: { label: 'mobile-320', viewport: { width: 320, height: 860 } },
  mobile390: { label: 'mobile-390', viewport: { width: 390, height: 844 } },
  tablet: { label: 'tablet-768', viewport: { width: 768, height: 1024 } },
  laptop: { label: 'laptop-1024', viewport: { width: 1024, height: 900 } },
  desktop: { label: 'desktop-1280', viewport: { width: 1280, height: 960 } },
  wide: { label: 'wide-1440', viewport: { width: 1440, height: 1080 } },
};

const ROUTE_AUDIT_MATRIX = [
  {
    id: 'home',
    route: (seed) => seed.routes.home,
    persona: 'public',
    devices: ['mobile320', 'mobile390', 'tablet', 'laptop', 'desktop', 'wide'],
    criticalAssertions: ['La page publique charge sans 404 et sans overflow horizontal.'],
    knownBlockers: [],
    status: 'active',
  },
  {
    id: 'login',
    route: (seed) => seed.routes.login,
    persona: 'public',
    devices: ['mobile320', 'mobile390', 'tablet', 'desktop'],
    criticalAssertions: ['La page de connexion reste lisible et le formulaire ne déborde pas.'],
    knownBlockers: [],
    status: 'active',
  },
  {
    id: 'fast-track',
    route: (seed) => seed.routes.fastTrack,
    persona: 'public',
    devices: ['mobile390', 'tablet', 'desktop', 'wide'],
    criticalAssertions: ['Le parcours fast-track garde ses CTA visibles.'],
    knownBlockers: [],
    status: 'active',
  },
  {
    id: 'passport-public',
    route: (seed) => seed.routes.passportStrong,
    persona: 'public',
    devices: ['mobile390', 'tablet', 'desktop', 'wide'],
    criticalAssertions: ['Le passeport public reste riche, masqué et responsive.'],
    knownBlockers: [],
    status: 'active',
  },
  {
    id: 'passport-verify',
    route: (seed) => seed.routes.verifyStrong,
    persona: 'public',
    devices: ['mobile390', 'tablet', 'desktop'],
    criticalAssertions: ['La route /verify reste alignée sur le rendu canonique.'],
    knownBlockers: [],
    status: 'active',
  },
  {
    id: 'guarantor-verify',
    route: (seed) => seed.routes.guarantorReview,
    persona: 'public',
    devices: ['mobile390', 'tablet', 'desktop'],
    criticalAssertions: ['Le tunnel garant s’ouvre sans erreur réseau ou de mise en page.'],
    knownBlockers: [],
    status: 'active',
  },
  {
    id: 'tenant-dashboard',
    route: (seed) => seed.routes.tenantDashboard,
    persona: 'tenant',
    devices: ['mobile390', 'tablet', 'desktop', 'wide'],
    criticalAssertions: ['Le dashboard locataire affiche les dossiers seedés sans casser la grille.'],
    knownBlockers: [],
    status: 'active',
  },
  {
    id: 'apply-review',
    route: (seed) => seed.routes.applyReview,
    persona: 'tenant',
    devices: ['mobile390', 'tablet', 'desktop'],
    criticalAssertions: ['Le chapitre Garantie reste pilotable et les zones d’upload restent visibles.'],
    knownBlockers: [],
    status: 'active',
  },
  {
    id: 'apply-visale',
    route: (seed) => seed.routes.applyVisale,
    persona: 'tenant',
    devices: ['mobile390', 'tablet', 'desktop'],
    criticalAssertions: ['Le mode Visale reste cohérent et sans débordement.'],
    knownBlockers: [],
    status: 'active',
  },
  {
    id: 'apply-success',
    route: (seed) => seed.routes.successStrong,
    persona: 'tenant',
    devices: ['mobile390', 'tablet', 'desktop'],
    criticalAssertions: ['La page succès réutilise le passeport sans faux état cassé.'],
    knownBlockers: [],
    status: 'active',
  },
  {
    id: 'owner-dashboard',
    route: (seed) => seed.routes.ownerDashboard,
    persona: 'owner',
    devices: ['tablet', 'laptop', 'desktop', 'wide'],
    criticalAssertions: ['Le cockpit propriétaire garde ses cartes et CTA stables.'],
    knownBlockers: [],
    status: 'active',
  },
  {
    id: 'owner-property-review',
    route: (seed) => seed.routes.ownerPropertyReview,
    persona: 'owner',
    devices: ['tablet', 'laptop', 'desktop', 'wide'],
    criticalAssertions: ['Le tunnel propriétaire détaillé reste exploitable avec contenu long.'],
    knownBlockers: [],
    status: 'active',
  },
  {
    id: 'lease-strong',
    route: (seed) => seed.routes.leaseStrong,
    persona: 'owner',
    devices: ['tablet', 'laptop', 'desktop', 'wide'],
    criticalAssertions: ['Le wizard de bail garde ses blocs, métriques et actions visibles.'],
    knownBlockers: [],
    status: 'active',
  },
];

module.exports = {
  DEVICES,
  ROUTE_AUDIT_MATRIX,
};
